### ISSUE TITLE
Crash On Launch

### ISSUE THREAD

**Issue by Boolyman** [Brian-Wuest/MC-FromTheDepths#1]
Hey Fellas,
   Was gonna try out the file you sent me, but it crashed when trying to load it with my pack.  So I tried it by itself with JEI being the only other mod, and made sure it was Forge 1.12.2-14.23.1.2559 but the crash still occurred.  Crash report attached.

[crash-2017-12-26_21.37.31-client.txt](https://github.com/Brian-Wuest/MC-FromTheDepths/files/1588405/crash-2017-12-26_21.37.31-client.txt)

**Comment by Brian-Wuest** [comment]
I uploaded a new version to that drive link I gave you. It was an issue with a dependency I thought would be there not actually being there.
