### ISSUE TITLE
Infinitely Recursive Altar NBT leading to eventual lockup and rollback

### ISSUE THREAD

**Issue by anabsolutesloth** [Brian-Wuest/MC-FromTheDepths#13]
Many users of the MC Eternal modpack, which features From the Depths as something in the Lategame used to summon customized bosses, have long been having issues with FTD's altars creating a new level of their NBT tag every tick they are loaded, it looks something like this:
```ForgeCaps:{
   ForgeCaps:{
      ForgeCaps:{
         ForgeCaps:{
            etc...
```
Eventually, the tag gets too big for the game to save properly, and ends up causing the world to lock up and usually roll back.

Minecraft-Eternal/MC-Eternal-1.12#160

**Comment by Brian-Wuest** [comment]
Once I am done testing a pretty major update which was pushed a month ago I will take a look at this defect. 

I am sorry this is taking so long but my time/attention is limited.
