### ISSUE TITLE
Feedback Alpha Build 1.0.0

### ISSUE THREAD

**Issue by Boolyman** [Brian-Wuest/MC-FromTheDepths#2]
Everything seems to be working well since the crash fix.  You mentioned options for the text above the Altar.  Is that something that will be in the config file?   For the purposes of my pack, I would turn it off.  But seeing as this will be released for public use, I don't know if that would be a useful feature for packs.  

The spawning of the mobs and boss works great.  My only takeaway would be: Do we want to have a bit of a delay between clicking the Totem onto the Altar, and the boss spawning?  A bit more of a dramatic entrance... a few seconds pass, a rumble, some tense sound effects, something?  Right now it seems very much like just plopping out a boss from a spawn egg.

**Comment by Brian-Wuest** [comment]
I can put the add spawning text as a config option.

As for the dramatic affect, I get where you are coming from. I cannot make new sound effects myself but what about lightning strikes on each block surrounding the altar? Obviously not at the same time. They would need to be staggered.

I am glad that everything is working out!

**Comment by Boolyman** [comment]
Yea, a few second delay and some lightning strikes will get the job done fine.

**Comment by Brian-Wuest** [comment]
Okay, I got something put together I think you will like and I updated the google drive location.

What's going to happen now is that a lightning bolt will strike on each cardinal direction around the block. 1 strike per second until 4 lightning strikes occur. Lightning strikes do NOT cause damage/fires, it's only the effect. On the 4th strike the boss is generated with it's own lightning strike. If there are any adds as part of this spawning, the adds also are "spawned" from a lightning strike.

I also put in a randomizer for where the monsters are spawned in relation to the altar. They will spawn within 3 blocks of the altar. They can still spawn on the altar but this will make it more interesting.

Please download the new copy and test things out. Please test things out in a dedicated server scenario to please.

**Comment by Boolyman** [comment]
Sorry about getting to this a bit late, I have had some medical things to address, and have surgery on my jaw tomorrow.  Anyways, I tested the new file and it looks great.  The timing is perfect, the effects are good to go.  Looking forward to seeing the progression from here.

**Comment by Brian-Wuest** [comment]
Awesome, from my end there isn't too much to do until I get the arena by Kaojinn.

**Comment by Boolyman** [comment]
Have you guys considered nixxing the big football field size arena?  What about just doing a fancy altar type setup... something diabolical looking about 10x10x10 size with some pillars and fire or something.  Cleaning up the spawn block textures and making sure the summoning is perfect.  That might be a bit more reasonable for your time schedules than trying to design a huge arena.

**Comment by Brian-Wuest** [comment]
I think that would be fine. I can forward this onto Kaojinn. He doesn't check here much :).

**Comment by Boolyman** [comment]
Have you been able to speak with Kaojinn?  I am determined to never press you guys for any progress, as this project is a huge help to my pack... but I just wanted to get an idea of whether or not I will be able to go into closed beta with the pack in the next month or so.

**Comment by Brian-Wuest** [comment]
I talked to him yesterday about this actually. He said that he was going to work on the summoningf area.

**Comment by Brian-Wuest** [comment]
To update you on our progress (and to make sure that we aren't dead). I designed the Altar of Summoning. It's got a nice sinister feel to it and it will really stand out.

The glowstone is just there for lighting :).

![altar of summoning](https://user-images.githubusercontent.com/13502068/36314214-bb7135fc-12f9-11e8-923f-2f8f09d87080.png)

**Comment by Boolyman** [comment]
Sorry for not checking back sooner, I have been in full pack dev mode.  Trying to get a very early beta access started this week... got a lot of people tapping their feet at me lol.  It looks good... I'm flexible... if you guys are happy, and it performs it's job, I can work with it.

**Comment by Brian-Wuest** [comment]
Closing this issue. I have uploaded a Beta build of this mod to CurseForge. With that we can start distributing builds, getting feedback and making updates!
