### ISSUE TITLE
Summon Syntax

### ISSUE THREAD

**Issue by Boolyman** [Brian-Wuest/MC-FromTheDepths#3]
I'm getting around to setting up the summons for the pack, but I don't see any example syntax anywhere of what the summon file is supposed to look like.  Can you provide an example of how I would write a summon for a boss, with NBT, etc...?

**Comment by Brian-Wuest** [comment]
Hi Boolyman, this isn't any different from how it was in the Alpha. Below is how you could create the NBT data for Zeus as well as create creeper adds for a Zombie boss.

I also put the simple example on the "Pages" tab of the project. 

https://minecraft.curseforge.com/projects/from-the-depths/pages/home/summon-info

When I get some time I will create a "Standard Bosses" file for vanilla.

I think most of this NBT data is standard except for what's in the "ForgeCaps" key.

```javascript
[
	{
		key: "Zombie",
		bossInfo: {
			domain: "minecraft",
			name: "zombie"
		},
		bossAddInfo: {
			domain: "minecraft",
			name: "creeper",
			spawnFrequency: 8,
			totalSpawnDuration: 64,
			nbtData: {}
		}
	},
	{
		key: "Zeus",
		bossInfo: {
			domain: "oldgods",
			name: "zeusmob",
			nbtData: {
				HurtByTimestamp: 0,
				Attributes: [{
						Base: 6000.0,
						Name: "generic.maxHealth"
					}, {
						Base: 0.0,
						Name: "generic.knockbackResistance"
					}, {
						Base: 0.3,
						Name: "generic.movementSpeed"
					}, {
						Base: 0.0,
						Name: "generic.armor"
					}, {
						Base: 0.0,
						Name: "generic.armorToughness"
					}, {
						Base: 16.0,
						Name: "generic.followRange"
					}, {
						Base: 60.0,
						Name: "generic.attackDamage"
					}
				],
				Invulnerable: false,
				FallFlying: false,
				PortalCooldown: 0,
				AbsorptionAmount: 0.0,
				FallDistance: 0.0,
				DeathTime: 0,
				ForgeCaps: {
					"lilliputian:size": {
						base_size: 2.75,
						scale: 1.0
					},
					"lycanitesmobs:iextendedentity": {}
				},
				HandDropChances: [0.085, 0.085],
				PersistenceRequired: false,
				id: "oldgods:zeusmob",
				Motion: [0.0, 0.0, 0.0],
				Leashed: false,
				UUIDLeast: -6099387858068449208,
				Health: 6000.0,
				LeftHanded: false,
				Air: 300,
				OnGround: false,
				Dimension: 0,
				Rotation: [1.0430988, 0.0],
				UpdateBlocked: 0,
				HandItems: [{}, {}],
				ArmorDropChances: [0.085, 0.085, 0.085, 0.085],
				UUIDMost: 4115808155355267147,
				CustomName: "Leader Of The Old Gods",
				Pos: [0.0, 0.0, 0.0],
				Fire: -1,
				ArmorItems: [{}, {}, {}, {}],
				CanPickUpLoot: false,
				HurtTime: 0,
				CustomNameVisible: true
			}
		}
	}
]
```

**Comment by Boolyman** [comment]
Perfect!  Thanks

**Comment by Brian-Wuest** [comment]
Closing issue.

**Comment by Boolyman** [comment]
I'm having trouble generating a second key.  This supports having more than one summoning totem registered, right?   Is my syntax for the 2nd boss correct?

https://pastebin.com/CNXJqa35

**Comment by Brian-Wuest** [comment]
Remove the "}" on lines 20 and 22. These are closing off the topmost "{" making this invalid JSON.

**Comment by Boolyman** [comment]
Ok, I made that change, but I still only see the summoning totem for the first boss in the config.  This pack will have 6-8 different bosses, so won't there be 6-8 different summoning totems in JEI based on the config files?

**Comment by Brian-Wuest** [comment]
I was able to get this to work. Here are some screen shots.

Shows that I have 2 items
![2018-04-05_05 07 18](https://user-images.githubusercontent.com/13502068/38360445-d1d23b14-388f-11e8-83c3-5b89b8013aff.png)

Shows the info for one item.
![2018-04-05_05 07 33](https://user-images.githubusercontent.com/13502068/38360446-d54ba1a4-388f-11e8-9d6f-37ebe42ce547.png)

Shows info for the other item.
![2018-04-05_05 07 36](https://user-images.githubusercontent.com/13502068/38360452-d74ca340-388f-11e8-9311-9114b00f3fee.png)

Here's the folder structure. File names for the "Summon_XXXXXX.json" files don't matter. That's just what I named it.
![folder structure](https://user-images.githubusercontent.com/13502068/38360454-d9d0a0da-388f-11e8-861a-4d6625b279d8.PNG)

Spawn info file, compressed for brevity.
![spawn info file](https://user-images.githubusercontent.com/13502068/38360495-f2da9a36-388f-11e8-89c8-04c21226c219.PNG)

The recipe for Zeus
![zeus recipe](https://user-images.githubusercontent.com/13502068/38360516-ff35b2ac-388f-11e8-9970-a913f15d5312.PNG)

**Comment by Boolyman** [comment]
I have skimmed over this vs my files literally a dozen times, letter by letter comparing syntax.  I have tried it with and without the "data" fields in the recipe.  It is simply not working.  The JSON checker website also claims there is an error in your first syntax for some reason.
![2018-04-05 20_58_15-greenshot](https://user-images.githubusercontent.com/24765883/38402932-94a93a14-3914-11e8-8b8b-080ca8ea75b7.png)
![2018-04-05 20_58_31-greenshot](https://user-images.githubusercontent.com/24765883/38402936-983148ca-3914-11e8-8982-cee819c91f8d.png)
![2018-04-05 20_58_40-greenshot](https://user-images.githubusercontent.com/24765883/38402937-99c05a5a-3914-11e8-939c-a0000bed9acb.png)

**Comment by Boolyman** [comment]
I figured out a way to get the totem by manually changing the NBT in game.  That will work for now.

**Comment by Brian-Wuest** [comment]
I think the syntax errors are there because there's no quotes around the property names but GSON loads it just fine. Can you send me your log file? Maybe there's something in there about an error with a recipe.

Also, what other mods do you have installed? I would like to try to duplicate this on my end as much as possible so that you don't have to continue to hack around this issue. 😄

**Comment by Boolyman** [comment]
I sent you a PM on curse with the info.  Also had a question... the script supports using the Custom Name field to change the name of the boss that's summoned, correct?

**Comment by Brian-Wuest** [comment]
I got the pack, thank you!

You have to supply nbt data (so all of it :( ) in order to have a custom name.

**Comment by Brian-Wuest** [comment]
I am such an idiot, don't know why I didn't see it earlier!

In your recipe file. The "data" property needs to be a number. Lose the double quotes around it and it will be fine.

![summon biff](https://user-images.githubusercontent.com/13502068/38454999-37a9073a-3a37-11e8-98e7-65730bd61b31.PNG)
+9

**Comment by Boolyman** [comment]
I'm pretty sure I tried that already, but I will double check.

**Comment by Boolyman** [comment]
You are right, it worked!  Could you elaborate a little on what you mean by providing all of the NBT data if I want to change the mobs name?  I tried it with the Zeus mob, who looks like it has all of his data, and the name didnt change.  Can you do one example for me, and then I should be able to just copy that syntax.

**Comment by Boolyman** [comment]
A lot of the things we have covered in this topic may be good on the wiki.  How to format the syntax of a totem recipe that includes meta data.  How to change the name of mobs that are spawned.

**Comment by Brian-Wuest** [comment]
It took a while but I got the custom name to show up. Apparently there are severe issues with using the NBT since it didn't work!

I have been getting it to work today but I am not ready to release an update for this.

I think I will see if I can set the custom name in my own settings so we don't have to supply ALL of the nbt data.

![2018-04-07_15 24 19](https://user-images.githubusercontent.com/13502068/38460043-db74d016-3a77-11e8-9bdb-a4e4fd8f71e4.png)


```
{
				"HurtByTimestamp": 0,
				"Attributes": [{
						Base: 20.0d,
						Name: "generic.maxHealth"
					}, {
						Base: 0.0d,
						Name: "generic.knockbackResistance"
					}, {
						Base: 0.23000000417232513d,
						Name: "generic.movementSpeed"
					}, {
						Base: 2.0d,
						Name: "generic.armor"
					}, {
						Base: 0.0d,
						Name: "generic.armorToughness"
					}, {
						Base: 35.0d,
						Name: "generic.followRange"
					}, {
						Base: 3.0d,
						Name: "generic.attackDamage"
					}, {
						Base: 0.04826679376871758d,
						Name: "zombie.spawnReinforcements"
					}
				],
				"Invulnerable": 0b,
				"FallFlying": 0b,
				"PortalCooldown": 0,
				"AbsorptionAmount": 0.0f,
				"FallDistance": 0.0f,
				"DeathTime": 0s,
				"HandDropChances": [0.085f, 0.085f],
				"PersistenceRequired": 0b,
				"id": "minecraft:zombie",
				"Motion": [0.0d, 0.0d, 0.0d],
				"Leashed": 0b,
				"UUIDLeast": -8628358549980592845L,
				"Health": 20.0f,
				"LeftHanded": 0b,
				"Air": 300s,
				"OnGround": 0b,
				"Dimension": 0,
				"Rotation": [0.7813014f, 0.0f],
				"UpdateBlocked": 0b,
				"HandItems": [{}, {}
				],
				"ArmorDropChances": [0.085f, 0.085f, 0.085f, 0.085f],
				"UUIDMost": -8778789817904576267L,
				"Pos": [0.0d, 0.0d, 0.0d],
				"CanBreakDoors": 0b,
				"Fire": -1s,
				"ArmorItems": [{}, {}, {}, {}
				],
				"CanPickUpLoot": 0b,
				"HurtTime": 0s,
				"CustomName": "This is a custom zombie!"
			}
		}
```

**Comment by Brian-Wuest** [comment]
I am working on adding Display Name, Maximum Health and Attack Damage to the spawnInfo.json file so you folks can specify that if wanted per monster. The NBT data field will go away since it's kinda buggy to do it that way :).

**Comment by Brian-Wuest** [comment]
Here's the spawnInfo.json format that I will be going with. It seems to work pretty well.

```
[{
		"key": "Zombie",
		"bossInfo": {
			"domain": "minecraft",
			"name": "zombie",
			"displayName": "Custom Zombie Yo!",
			"maxHealth": 40,
			"attackDamage": 10.5,
			"alwaysShowDisplayName": true
		},
		"bossAddInfo": {
			"domain": "minecraft",
			"name": "creeper",
			"displayName": "Custom Creaper!",
			"maxHealth": 5,
			"attackDamage": 5,
			"alwaysShowDisplayName": false,
			"spawnFrequency": 4,
			"totalSpawnDuration": 16
		}
	}
]
```

Here are some screen shots showing what a custom creeper and zombie looks like. They have reduced health and a different display name. The custom zombie has a ton of health, hits hard and always shows its name. It will even show the name on JourneyMap.

![2018-04-07_19 33 55](https://user-images.githubusercontent.com/13502068/38461652-b1abec96-3a9b-11e8-8278-106acdae837e.png)

![2018-04-07_19 34 02](https://user-images.githubusercontent.com/13502068/38461653-b83df5b8-3a9b-11e8-9831-6a4cd2e62b72.png)

**Comment by Boolyman** [comment]
Thats perfect!  Ive been wrestling with the NBT for hours now lol.  I will wait for this update.

**Comment by Brian-Wuest** [comment]
It is currently under review on curse.

Here's the link to the documentation on the json file stuff. I think I set you up as a contributor so you can change it if needed.

https://minecraft.curseforge.com/projects/from-the-depths/pages/home

**Comment by Brian-Wuest** [comment]
It has been approved. Version 1.1.0.0 is now ready for download and testing.

**Comment by Brian-Wuest** [comment]
Also something I should mention with regards to recipes. If there is an issue with your recipe syntax it is typically printed out in the log file usually saying something about malformed json or something along those lines. It should give you an idea of what's wrong with the recipe file 😸 ,

**Comment by Boolyman** [comment]
ok, thanks for all your help.  The pack comes out on Thursday.   I'm excited.

**Comment by Boolyman** [comment]
What if there is a boss that does not require adds to spawn with it?  This is not an issue, im just wondering.

**Comment by Brian-Wuest** [comment]
Then don't have that part of the JSON. Adds  are optional.

**Comment by Brian-Wuest** [comment]
Closing this since the mod is released with updated summon syntax.
