### ISSUE TITLE
Recipe and Summoning Dont Work

### ISSUE THREAD

**Issue by Boolyman** [Brian-Wuest/MC-FromTheDepths#4]
NVM, I think I know what happened.  Dont mind me.

**Comment by Brian-Wuest** [comment]
Okay, closing issue.

**Comment by Boolyman** [comment]
Sorry, had to take this down when I thought it was an issue on my end.  But I had a brain fart about the release date of the last update.

Anyways, the problem still persist.  The recipes arent working, the totems arent showing in JEI, and the summons wont summon... on a server.  But in SP everything works fine
.

**Comment by Brian-Wuest** [comment]
This is working on a dedicated server I have on my machine.

Both sides need to have the same summon and recipe files otherwise it won't work. When you confirm this and are still having an issue please provide logs from the client and the server and I will try to see what I can do.

Here's a screen shot.

![server summoning](https://user-images.githubusercontent.com/13502068/38864090-3b3b0496-41ff-11e8-8b7e-22845882302e.png)

**Comment by Brian-Wuest** [comment]
I also verified that the recipe is working properly on a server. It shows up in JEI and I am able to craft the totem with the custom recipe and the crafted item will spawn the correct monster.

**Comment by Boolyman** [comment]
Ok.  I will wait to see if it gets reported more.  Its a bit difficult when I dont have a server myself.

**Comment by DingoX3** [comment]
Using version from_the_depths-1.1.0.0
We are able to craft the Undying totem. Thats it. We are not able to craft any other totems including the Biff totem. I made a detailed imgur screenshots album to try and help define and describe the issues better. Please let me know if I can help in any way by testing new versions or single files that might help. I would love to see this implemented and working properly on servers like it does in single player. I have also done this on a new fresh server with a new world and all files uploaded without any changes.(i have 2 servers. I'm doing this on my test server so it wont interrupt our players on the other one. Which is also having the same issues.)

[Please look here at the images I provided](https://imgur.com/a/BB9ko)

**Comment by DingoX3** [comment]
Sorry forgot to include a log from the test server
[latest.log](https://github.com/Brian-Wuest/MC-FromTheDepths/files/1925291/latest.log)

**Comment by Brian-Wuest** [comment]
Alrighty, the only way I was able to duplicate this was if the FTD_Summons folder had nothing in it on the server side but had stuff on the client-side. Because of how JEI works it looks like it shows up properly but is not REALLY craftable. 

Once I made sure that the Server side had the same files as client-side it worked fine.

I am not sure how that "config\FTD_Summons" folder got created so maybe delete that? What Operating System are you running? I am running windows and it works fine.

Last thing is, are you doing this inside a building? Can you try this outside?

**Comment by DingoX3** [comment]
Ok thanks for looking into this. Its a rented server from nodecraft so Im really not sure if its windows or Linux. I did try it outside of a building in the open, nothing happened. I spent 6 hours today on my test server starting, stopping, moving files and making sure the files were the same. Im not new at setting up servers and i cant get it to work so im not sure what it is and im past the point of frustration. Im going to just cheat the spawn eggs in for the players until we are done with the pack. thanks again for responding.

**Comment by Brian-Wuest** [comment]
I am downloading the modpack and the associated server file list now. I will try to duplicate this using the modpack, with work/life it may be until later today that I will have more information.

**Comment by Brian-Wuest** [comment]
That didn't take as long as I thought it would. I got the mod pack installed and pulled the 1.0.5 server files. Got the server up and running and logged in. I did not change any configuration files for the server or client, just copy/paste then run.

I cheated in the Altar of Summoning (The original name for "Altar of Time" :smile:).

I also cheated in a totem or two and verified that it worked. I then crafted  a totem for Aphrodite and tried to summon with that, and that also worked.

This was still all on my machine.

Here's a screen shot from me logged into the server after I summoned Aphrodite.

![server summoning](https://user-images.githubusercontent.com/13502068/38988209-02aa806c-4398-11e8-8d8c-dccf6ec7868b.png)

**Comment by Boolyman** [comment]
I'm getting more reports of it not working, from other servers.  This is frustrating, since it cant be duplicated on your end.

**Comment by Boolyman** [comment]
It seems that on the servers reporting the issue, the FTD_Summons folder is empty.  But in the download I send out, the zip shows the files in it.  Can you think of any reason why the folder would go empty?

**Comment by Boolyman** [comment]
So I just spoke with Dingo and figured out that a folder is being installed in the instance called \FTD_summons..... not in the config, but in the actual instance directory.  Do you know why this would happen?  Deleting it and then replacing the FTD_summons inside the config folder fixes the issue... BUT, every server running this pack shouldnt have to put in an issue tracker to figure that out.  Is there something in the mod creating this folder?

Apparently it is a Linux server.  Does that have anything to do with it?

**Comment by Brian-Wuest** [comment]
This being Linux could have something to do with this. And yes I create the Folder when it doesn't exist. I will have to double check this creation code or just remove it and print a warning if no spawn info or recipes are found.

I was hoping that this wouldn't be an issue on Linux but I guess I was wrong. I don't use Linux so I was crossing my fingers.

**Comment by Brian-Wuest** [comment]
Okay, I think I figured it out. I was putting a hard back-slash for the sub folder instead of using the Paths class to create a Path. 

I will be uploading a new version soon.

**Comment by Brian-Wuest** [comment]
It has been uploaded to Curseforge. Should be available in less than an hour. 

Edit: It is available now. Please verify that this update addresses the issue

I know this was a huge bug on my side and I am really sorry. 

Thank you for all of your patience with this!

**Comment by Boolyman** [comment]
Thanks for your help!  Ill let you know.

**Comment by Boolyman** [comment]
I think that \FTD_summons folder has stopped showing up in the instance folder... but the one inside the config folder is still empty on install.  I've been having to manually send the servers reporting an issue the file in a zip

**Comment by Brian-Wuest** [comment]
Is that empty folder happening on servers (linux) of were you also able to duplicate it on your windows machine?

**Comment by Brian-Wuest** [comment]
Also, were you able to harvest log files? I added some additional logging in that last update.

Specifically if you see the below message then it somehow didn't see the directory and re-created it.

From The Depths: The summons directory doesn't exist, creating this directory

**Comment by Brian-Wuest** [comment]
@Boolyman, I uploaded a new version of the mod (1.1.0.2). This includes updated logging as well as new/better ways of reading the summon files. 

This update makes it so that the mod no longer creates the FTD_Summons folder so we shouldn't have the problem where it somehow get's overwritten with nothing.

The logging updates also include the mod name in the description so we can narrow down the recipe reading issues better.

**Comment by Boolyman** [comment]
Sounds great! Ill put out an update.

**Comment by Brian-Wuest** [comment]
Since it's been a while and no new issues have been reported I will close this issue. Please create a new one if there are further problems.

Thank you!
