### ISSUE TITLE
Crash with Latest Forge

### ISSUE THREAD

**Issue by NormanNormalington** [Brian-Wuest/MC-FromTheDepths#5]
Game crashed during launch, with only Forge 14.23.3.2678 for MC 1.12.2, and From the Depths 1.1.0.2. 

Crash Log:
https://gist.github.com/NormanNormalington/d5885863f8b81386e123a55a192c2203

**Comment by Brian-Wuest** [comment]
I have some follow up questions.
Did your FTD_Summons directory not exist for some reason? 

If you run the game again does the issue go away? 

Is this on a hosted server or on your local machine? 

What operating system are you running (just high level, mac windows or linux)?

If you downgrade to 2376 of forge does this issue go away?

**Comment by NormanNormalington** [comment]
No clue why the FTD_Summons directory isn't there. This is my first time loading the mod in this instance.
If I run the game again, I get the same crash.
This is just on my local machine. 
Operating System - Windows.
Downgrading to forge 2376 still gives me the same crash. 

Ok... So it seems I've found a fix. Manually creating a FTD_Summons folder in the config folder before launching with the mod seems to prevent it from crashing.

**Comment by Brian-Wuest** [comment]
Ah yeah, you have to create the folder manually with the latest release as there were some issues with automatically creating the folder. However, there should not be a run-time error like that. I will see what I can do to make sure that the run-time error doesn't occur.

**Comment by Brian-Wuest** [comment]
This is fixed with version 1.1.0.3 which has been approved.
