### ISSUE TITLE
infinite loop in code

### ISSUE THREAD

**Issue by Saereth** [Brian-Wuest/MC-FromTheDepths#8]
in a skyblock map with a small summoning platform this does and will consistently result in an infinite loop
https://github.com/Brian-Wuest/MC-FromTheDepths/blob/72c42283e9a40a7dbe02be10bbc941b96419e29f/src/main/java/com/wuest/from_the_depths/EntityInfo/BossInfo.java#L154-L157

proof in action:
https://i.imgur.com/S8ixmXK.png

**Comment by Brian-Wuest** [comment]
Must be because whatever is in the skyblock isn't considered "Air".

I can put a cap of 20 blocks on that in order to avoid an infinite loop in this case but it's still weird that it's not considered air.

**Comment by Brian-Wuest** [comment]
This has been fixed with version 1.1.0.8 which has been uploaded and approved on CurseForge.
