### ISSUE TITLE
Add ability for one boss to summon multiple minions

### ISSUE THREAD

**Issue by Jackiecrazy** [Brian-Wuest/MC-FromTheDepths#9]
like a super strong zombie with its smaller zombie minions and a little side dish of skeleton escorts, or an enderman assassin who spawns with both endermite and silverfish underlings. Is pretty cool, is all.

**Comment by Brian-Wuest** [comment]
This is a pretty sweet idea. I will look into this after I update the mod to 1.14. I am currently working through Prefab since that is my largest mod.

**Comment by Brian-Wuest** [comment]
Update: This is being worked on with my next big update.

This is being done for 1.12.

**Comment by Brian-Wuest** [comment]
Forgot to close this. 

This was done back in July with the 1.2 release.
